name: json_rpc_2
version: 2.0.4+1
author: Dart Team <misc@dartlang.org>
description: An implementation of the JSON-RPC 2.0 spec.
homepage: http://github.com/dart-lang/json_rpc_2
dependencies:
  stack_trace: '>=0.9.1 <2.0.0'
  stream_channel: '^1.1.0'
dev_dependencies:
  test: "^0.12.28"
environment:
  sdk: ">=1.8.0 <2.0.0"
