name: json_rpc_2
version: 2.2.0
description: >-
  Utilities to write a client or server using the JSON-RPC 2.0 spec.
homepage: https://github.com/dart-lang/json_rpc_2

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  pedantic: ^1.8.0
  stack_trace: ^1.0.0
  stream_channel: ">=1.1.0 <3.0.0"

dev_dependencies:
  test: ^1.0.0
